/*SENTENCIA CASE
CASE
  WHEN CONDICION_1 THEN RESULTADO_1
  WHEN CONDICION_2 THEN RESULTADO_2
  ..... CONDICIONES POSIBLES
  ELSE RESULTADO_PREDETERMINADO
END
*/

--CREAR UN DDL DE LA ENTIDAD LIBRO
CREATE TABLE LIBRO(
   ID_LIBRO NUMBER,
   NOMBRE NVARCHAR2(100),
   AUTORN VARCHAR2(100),
   GENERO NUMBER, --1 DRAMA, -2 TERROR, 3 CIENCIA FICCION, 4 NOVELA, 5 THIRLLER, 6 COMEDIA
   NO_PAGINAS NUMBER,
   PRECIO NUMBER,
   EDITORIAL  NVARCHAR2(100),
   CONSTRAINT LIBRO_PK PRIMARY KEY(ID_LIBRO)
);
INSERT INTO LIBRO VALUES (1,'FLORES EN EL ATICO','VC.ANDREWS',0,600,550,'DE BOLSILLO');
INSERT INTO LIBRO VALUES (2, 'cEMENTERIO DE ANIMALES', 'STEPHEN KING', 0, 550, 750, 'DE BOLSILLO');
INSERT INTO LIBRO VALUES (3,'IT','STEPHEN KING',2,250,350,'GARCIA');
INSERT INTO LIBRO VALUES(4, 'LA LADRONA DE LIBROS', 'ELENA MARQUEZ', 1, 250, 600, 'COMETA');
INSERT INTO LIBRO VALUES (5,'CRONICA DE UNA MUERTE ANUNCIADA','GABRIEL GARCIA MARQUEZ',0,350,250,'ALFAGUARA');
INSERT INTO LIBRO VALUES(6, 'LA CASA DE LAS SOMBRAS', 'TRAD. SIMON SAITO', 2, 600, 750, 'MINOTAURO');
COMMIT;
SELECT * FROM LIBRO;
--USO DE SENTENCIA CASE

SELECT ID_LIBRO, NOMBRE, AUTORN,
(
     CASE GENERO
     WHEN 1 THEN 'DRAMA'
     WHEN 2 THEN 'TERROR'
     WHEN 3 THEN 'CIENCIA FICCION'
     WHEN 4 THEN 'NOVELA'
     WHEN 5 THEN 'THIRLLER'
     WHEN 6 THEN 'COMEDIA'
     ELSE 'SIN GENERO'
     END
) AS GENERO, NO_PAGINAS, PRECIO, EDITORIAL FROM LIBRO;

-- 
SELECT ID_LIBRO,NOMBRE,AUTORN,GENERO,NO_PAGINAS,
(
   CASE 
   WHEN PRECIO > 400 THEN ' ES CARO ' || TO_CHAR(PRECIO, '$9,999.00') || 'PESOS'
   WHEN PRECIO <= 400 THEN ' ES BARATO ' || TO_CHAR(PRECIO, '$9,999.00') || 'PESOS'
   ELSE ' PRECIO NO DEFINIDO'
   END
) AS PRECIO, EDITORIAL FROM LIBRO;
   
--REALIZAR PRACTICA CON EL USO DE LA SENTENCIA CASE, USAR DIFERENTE ENTIDA Y EJEMPLOS
CREATE TABLE BOTELLA(
   ID_BOTELLA NUMBER,
   FUNDADOR NVARCHAR2(100),
   MARCA VARCHAR2(100),
   AÑOS NUMBER, -- 0 MANJAR, -DE 1 A 9 DISFRUTA, MAYOR DE 10 DELEITA
   CONTENIDO NUMBER,
   PRECIO NUMBER,
   CONSTRAINT BOTELLA_PK PRIMARY KEY(ID_BOTELLA)
);
INSERT INTO BOTELLA VALUES (1,'TIO JACK','JACK DANIELS',15,3000 ,800);
INSERT INTO BOTELLA VALUES (2, 'JOHIE W.', 'BLUE LABEL', 0, 750,8000);
INSERT INTO BOTELLA VALUES (3,'ERNESTO MALL','THE MALLACAN',0,750,4675);
INSERT INTO BOTELLA VALUES(4, 'PABLITO', 'PASS PORT', 3,3000, 250);
INSERT INTO BOTELLA VALUES (5,'ARTHUR ABSOLU','ABSOLUT VODKA',5,1000,450);
INSERT INTO BOTELLA VALUES(6, 'HERMANOS HOUSE', 'BLACK AND WHITE', 12, 1750, 932);
COMMIT;
SELECT * FROM BOTELLA;
DELETE FROM BOTELLA WHERE ID_BOTELLA = 3;
SELECT ID_BOTELLA, FUNDADOR, MARCA,AÑOS,CONTENIDO,
(
   CASE 
   WHEN PRECIO <= 600 THEN ' ACCESIBLE ' || TO_CHAR(PRECIO, '$9,999.00') || 'PESOS'
   WHEN PRECIO  > 601 AND PRECIO <2000 THEN ' ES CARO ' || TO_CHAR(PRECIO, '$9,999.00') || 'PESOS'
   WHEN PRECIO  > 3000 THEN ' AHORRA ' || TO_CHAR(PRECIO, '$9,999.00') || 'PESOS' 
   ELSE ' PRECIO NO DEFINIDO'
   END
) AS PRECIO FROM BOTELLA;
SELECT ID_BOTELLA, FUNDADOR, MARCA,
(
   CASE 
   WHEN AÑOS >= 1 AND AÑOS <9 THEN ' DISFRUTA ' 
   WHEN AÑOS  > 10  THEN ' DELEITA ' 
   WHEN AÑOS  = 0 THEN ' MANJAR '
   ELSE ' NO DEFINIDO'
   END
) AS AÑOS,CONTENIDO,PRECIO FROM BOTELLA;

-- 

