--CREACION DE DDLL
CREATE TABLE AUTOMOVIL(
ID_AUTO NUMBER,
MARCA NVARCHAR2(100),
SUB_MARCA NVARCHAR2(100),
MODELO NUMBER,
COLOR NVARCHAR2(100),
PRECIO NUMBER,
VERSION NVARCHAR2(100),
CONSTRAINT AUTOMOVIL_PK PRIMARY KEY(ID_AUTO)
);

INSERT INTO AUTOMOVIL VALUES(1, 'NISSAN', 'SENTRA', 2001, 'NEGRO', 250500, 'NORMAL');
INSERT INTO AUTOMOVIL VALUES(2, 'CHEVROLET', 'CAVALIER', 2023, 'AZUL', 250500, 'NORMAL');
INSERT INTO AUTOMOVIL VALUES(3, 'FORT', 'MUSTANG', 2000, 'NEGRO', 346930, 'DEPORTIVO');
INSERT INTO AUTOMOVIL VALUES (4, 'AUDI', 'R8', 2020, 'ROJO', 700000, 'DEPORTIVO');
INSERT INTO AUTOMOVIL VALUES (5, 'VOCHO', 'VOCHO', 1993, 'NARANJA', 80000, 'PEQUENO');
INSERT INTO AUTOMOVIL VALUES(6,'ZENTRONO','SOG',2014,'MORADO',530000,'FURY');
INSERT INTO AUTOMOVIL VALUES(7,'ASTRO','RG',2020,'BLANCO',630000,'AVO');
INSERT INTO AUTOMOVIL VALUES(8, 'HONDA', 'CIVIC', 2004, 'NEGRO', 530000, 'DEPORTIVO');
INSERT INTO AUTOMOVIL VALUES(9, 'TOYOTA', 'SIENNA', 2014, 'AZUL', 700000, 'FAMILIAR');
COMMIT;

SELECT * FROM AUTOMOVIL;
/*
EJERCICIO A REALIZAR LAS SIGUIENTES SENTENCIAS
1 MOSTRAR LA INFORMACION ORDENADA DE LOS AUTO DE ACUERDO A SU PRECIO DE MAYOR A MENOR ADEMAS DE AGREGAR EL SIGNO DE PESOS: $ EN EL PRECIO 
Y SEPARAR POR COMAS LOS MILES CON DOS DECIMALES EJEMPLO(400,00.00)
2 BUSCAR LOS AUTO QUE EN LA SUB MARCA CONTENGA UNA LETRA 'E' Y SACAR EL PROMEDIO DE SU PRECIO. APLICAR FORMATO
3 MOSTRAR LOS AUTO QUE CUESTEN 700,000 O MAS Y CAMBIAR LAS LETRAS A MINISCULAS DE LA MARCA Y SUB_MARCA
4 CONSULTAR LOS REGISTROS QUE NO SEAN NULOS EN LA VERSION Y QUE SU PRECIO SEA MAYOR A 500MIL Y ORDENAR DE MENOR A MAYOR
5 MOSTRAR LOS AUTOMOVILES QUE SU PRECIO SEA MAYOR A 500 MIL PERO MENOR A 800 MIL
6 BUSCAR LOS AUTOMOVILES QUE SEAN NEGRO Y AGREGAR EL PRECIO Y LA PALABRA PESOS AL FINAL($400,000.00 PESOS)
7 CONTAR CUANTOS AUTO TENGO DE CADA MARCA E INDICAR LA MARCA QUE PERTENECE CADA CONTEO
8 MOSTAR EL REGISTRO QUE TENGA EL PRECIO MAS ALTO Y DAR FORMAT AL PRECIO
9 MOSTRAR EL AUTO MAS ANTIGUO Y AGREGAR FORMATO AL PRECIO Y EN EL MODELO AGREGAR LA PALABRA AÑO(AÑO 1990)
10 DESGLOSAR EL DETALLE DE LOS AUTOS(CONCAT O PIPE)
*/
-- 1
SELECT ID_AUTO,MARCA,SUB_MARCA,MODELO,COLOR, TO_CHAR(PRECIO, '$000,000.00') AS PRECIO, VERSION  FROM AUTOMOVIL ORDER BY PRECIO DESC;

--2
SELECT * FROM AUTOMOVIL WHERE SUB_MARCA LIKE '%E%';
SELECT TO_CHAR (AVG(PRECIO), '$000,000.00') AS PROMEDIO  FROM AUTOMOVIL 
WHERE SUB_MARCA LIKE '%E%';

--3
SELECT ID_AUTO,LOWER(MARCA),LOWER(SUB_MARCA),MODELO,COLOR, TO_CHAR(PRECIO, '$000,000.00') AS PRECIO, VERSION FROM AUTOMOVIL WHERE PRECIO >= 700000;

--4
SELECT * FROM AUTOMOVIL WHERE VERSION IS NOT NULL AND PRECIO > 500000 ORDER BY PRECIO ASC;

--5
SELECT ID_AUTO,MARCA,SUB_MARCA,MODELO,COLOR, TO_CHAR(PRECIO, '$000,000.00') AS PRECIO, VERSION   FROM AUTOMOVIL 
WHERE PRECIO BETWEEN 500000 AND 800000;

--6
SELECT ID_AUTO,MARCA,SUB_MARCA,MODELO,COLOR, TO_CHAR(PRECIO, '$000,000.00')|| 'PESOS' AS PRECIO, VERSION  FROM AUTOMOVIL 
WHERE COLOR = 'NEGRO';

-7
SELECT MARCA, COUNT(ID_AUTO) AS NU_AUTOS FROM AUTOMOVIL WHERE MARCA IS NOT NULL GROUP BY MARCA; 

--8
SELECT ID_AUTO,MARCA,SUB_MARCA,'AÑO ' || MODELO,COLOR, TO_CHAR(PRECIO, '$000,000.00')|| 'PESOS' AS PRECIO, VERSION FROM AUTOMOVIL
WHERE PRECIO = (SELECT MAX(PRECIO) FROM AUTOMOVIL);

--9
SELECT ID_AUTO,MARCA,SUB_MARCA,'AÑO ' || MODELO,COLOR, TO_CHAR(PRECIO, '$000,000.00')|| 'PESOS' AS PRECIO, VERSION FROM AUTOMOVIL
WHERE PRECIO = (SELECT MIN(PRECIO) FROM AUTOMOVIL);

--10
SELECT 'EL AUTO ' || ID_AUTO || ' MARCA ' || MARCA || ' MODELO ' ||SUB_MARCA || ' AÑO ' ||MODELO ||' CON COLOR '|| COLOR || ' Y PRECIO ' || 
PRECIO || ' EN LA ' || VERSION AS DETALLE FROM AUTOMOVIL;

