--trigger a nivel sentencia
DELETE FROM COMPUTADORA;
DELETE FROM BIT_COMPUTADORA;

CREATE OR REPLACE TRIGGER TR_I_U_D_COMPUTADORA
AFTER INSERT OR UPDATE OR DELETE ON COMPUTADORA
DECLARE
     LV_ID_BIT NUMBER;
     LV_USUARIO NVARCHAR2(100);
     LV_FECHA DATE;
     LV_MOV NVARCHAR2(100);
  BEGIN
     --RECUPERAR ID VALIDO CON SECUENCIA
     SELECT S_ID_BIT_COMPU.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;
     
     IF INSERTING THEN
        LV_MOV := 'INSERT';
    ELSIF UPDATING THEN
        LV_MOV := 'UPDATE';
    ELSIF DELETING THEN
        LV_MOV := 'DELETE';
    
    END IF;
      INSERT INTO BIT_COMPUTADORA(ID_BIT, USUARIO, FECHA_MOV, MOVIMIENTO)
      VALUES(LV_ID_BIT, LV_USUARIO, LV_FECHA, LV_MOV);
 END TR_I_U_D_COMPUTADORA;
 /
 
INSERT INTO COMPUTADORA VALUES(1, 'DELL', 'INSPIRON', 16, 'INTEL CORE i5', 110000);
INSERT INTO COMPUTADORA VALUES(2, 'LENOVO', 'THINK PAD', 32, 'INTEL CORE i3', 12000);
INSERT INTO COMPUTADORA VALUES(3, 'HP', 'INPIRON', 8, 'TYZEN 3', 7859);
COMMIT;

SELECT * FROM COMPUTADORA; 
SELECT ID_BIT, FECHA_MOV, MOVIMIENTO FROM BIT_COMPUTADORA;
DELETE FROM COMPUTADORA;

------------------------
-- TRIGGER A NIVEL SENTENCIA TABLA VIDEOJUEGO

CREATE OR REPLACE TRIGGER TR_I_U_D_VIDEOJUEGO
AFTER INSERT OR UPDATE OR DELETE ON VIDEOJUEGO
DECLARE
     LV_ID_BIT NUMBER;
     LV_USUARIO NVARCHAR2(100);
     LV_FECHA DATE;
     LV_MOV NVARCHAR2(100);
  BEGIN
      SELECT S_ID_BIT_JUEGO.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;
      
       IF INSERTING THEN
        LV_MOV := 'INSERT';
    ELSIF UPDATING THEN
        LV_MOV := 'UPDATE';
    ELSIF DELETING THEN
        LV_MOV := 'DELETE';
    END IF;
    
     INSERT INTO BIT_VIDEOJUEGO(ID_BIT, USUARIO, FECHA_MOV, MOVIMIENTO)
      VALUES(LV_ID_BIT, LV_USUARIO, LV_FECHA, LV_MOV);
    END TR_I_U_D_VIDEOJUEGO;
    /
    INSERT INTO VIDEOJUEGO VALUES(1, 'GOD OF WAR', 'C', 1599); 
    INSERT INTO VIDEOJUEGO VALUES(2, 'TLOU', 'B+', 1299); 
    INSERT INTO VIDEOJUEGO VALUES(3, 'MARIO', 'A', 700);
    COMMIT;
    SELECT * FROM VIDEOJUEGO;
    SELECT ID_BIT,USUARIO, FECHA_MOV, MOVIMIENTO FROM BIT_VIDEOJUEGO;
    UPDATE VIDEOJUEGO SET NOMBRE ='DIOS', CATEGORIA ='B', COSTO =321 WHERE ID_JUEGO =1;
    UPDATE VIDEOJUEGO SET NOMBRE ='JUAN', CATEGORIA ='AA', COSTO =007 WHERE ID_JUEGO =3;
    DELETE VIDEOJUEGO;
    DELETE BIT_VIDEOJUEGO;
    
