--SECUENCIA PARA BIT_COMPUTADORA;
--SECUENCIA O SEQUENCE ES UN BLOQUE PL/SQL QUE SE EMPLEA PARA GENERAR INCREMENTOS A UN NUMERO ENTERO ASEGURANDO Y ASIGNANDOLOS A LAS LLAVES PRIMARIAS
--PARA ASEGURAAR QUE NO SEAN REPETIDAS

CREATE SEQUENCE S_ID_BIT_COMPU
START WITH 1
MAXVALUE 9999
MINVALUE 1
NOCYCLE;
/
--SELECT S_ID_BIT_COMPU.NEXTVAL FROM DUAL;


