--LOD CURSORES SON ERRAMIENTAS PARA REALIZAR OPERACIONES SOBRE RESULTADOS DE MANERA SECUENCIAL

SELECT * FROM LIBRO;

CREATE OR REPLACE PROCEDURE PR_DETALLE_LIBRO
IS
     CURSOR LIBRO_INFO IS
        SELECT NOMBRE,
          (
            CASE GENERO
              WHEN 1 THEN 'DRAMA'
              WHEN 2 THEN 'TERROR'
              WHEN 3 THEN 'CIENCIA FICCIONE'
              WHEN 4 THEN 'NOVELA'
              WHEN 5 THEN 'THRILLER'
              WHEN 6 THEN 'COMEDIA'
              ELSE 'SIN GENERO'
          END
        )AS GENERO, PRECIO FROM LIBRO;
        --VARIABLES LOCALES
        LV_NOMBRE LIBRO.NOMBRE%TYPE;
        LV_GENERO NVARCHAR2(100);
        LV_PRECIO NUMBER;
    BEGIN
    OPEN LIBRO_INFO;
    
    --RECUPERAR EL CURSOR Y MOSTRAR LOS DATOS
    LOOP
      --POR CADA FILA RECORIDA SE TOMARAN LOS DATOS DEL CURSOR
      FETCH LIBRO_INFO INTO LV_NOMBRE, LV_GENERO, LV_PRECIO;
      --CONDICION PARA SALIR CUANDO EL CURSOR YA NO TENGA REGISTROS
      EXIT WHEN LIBRO_INFO%NOTFOUND;
      
      --MOSTRAR LOS DATOS DEL CURSOR
      DBMS_OUTPUT.PUT_LINE('NOMBRE DEL LIBRO: '||LV_NOMBRE||', GENERO: '||LV_GENERO||', PRECIO: '||LV_PRECIO);
      END LOOP;
    --CERRAR EL CURSOR
    CLOSE LIBRO_INFO;
END PR_DETALLE_LIBRO;
/

BEGIN 
  PR_DETALLE_LIBRO;
  END;
  /


--EJERCICIO REALIZAR DE LA TABLA QUE USUARON PARA LA PRACTICA DE CASE

SELECT * FROM BOTELLA;

CREATE OR REPLACE PROCEDURE PR_DETALLE_BOTELLA
IS
     CURSOR BOTELLA_INFO IS
        SELECT MARCA,
          (
            CASE 
              WHEN AÑOS >= 1 AND AÑOS <9 THEN ' DISFRUTA ' 
              WHEN AÑOS  > 10  THEN ' DELEITA ' 
              WHEN AÑOS  = 0 THEN ' MANJAR '
              ELSE ' NO DEFINIDO'
              END
        )AS AÑEJAMIENTO, PRECIO FROM BOTELLA;
        --VARIABLES LOCALES
        LV_MARCA BOTELLA.MARCA%TYPE;  --AQUI TYPE SIRVE PARA PODER TRAER CUALQUIER RESULTADO YA SEA NULL O NO 
        LV_AÑOS NVARCHAR2(100);
        LV_PRECIO NUMBER;
    BEGIN
    OPEN BOTELLA_INFO;
  LOOP
      --POR CADA FILA RECORIDA SE TOMARAN LOS DATOS DEL CURSOR
      FETCH BOTELLA_INFO INTO LV_MARCA, LV_AÑOS, LV_PRECIO;
      --CONDICION PARA SALIR CUANDO EL CURSOR YA NO TENGA REGISTROS
      EXIT WHEN BOTELLA_INFO%NOTFOUND;
      --MOSTRAR LOS DATOS DEL CURSOR
      DBMS_OUTPUT.PUT_LINE('LA MARCA ES : '||LV_MARCA||', SU AÑEJAMIENTO SE PUEDE: '||LV_AÑOS||', PRECIO: '||LV_PRECIO);
      END LOOP;
    --CERRAR EL CURSOR
    CLOSE BOTELLA_INFO;
END PR_DETALLE_BOTELLA;
/
BEGIN 
  PR_DETALLE_BOTELLA;
  END;
  /
