--CREACION DE UNENTIDAD

/*
CHAR: ALMACENA DATOS DE LONGITUD
VARCHAR:
VARCHAR2: SOLO ES ORACLE
NVRCHAR2: ESPECIFICO DE ORACLE, SE UTILIZA PARA LAMACENAR CARATERES DE LONGITUD VARIABLE DE CARATER UNICO
*/

--DDL
CREATE TABLE EMPLEADO(
ID_EMPLEADO NUMBER,
NOMBRE NVARCHAR2(100),
APELLIDO_P NVARCHAR2(100),
EDAD NUMBER,
PUESTO NVARCHAR2(100),
DEPARTAMENTO NVARCHAR2(100)
);

--DML
INSERT INTO EMPLEADO VALUES(1,'JULIAN', 'RODRIGEZ', 37, 'ENCARGADO DE NOMINAS', 'RH');
COMMIT;


SELECT * FROM EMPLEADO;

--EJECUTAR UN DML PARA ELIMINAR LOS REGISTROS DE UNA TABLA
DELETE FROM EMPLEADO;  --ELIMINA SOLO LOS REGISTROS DE MI TABLA
--EJECUTAR UNDDL PARA ELIMINAR LA TABLA
DROP TABLE EMPLEADO;  -- ELIMINA TODA LA TABLA

--USO DE LOS CONSTRAIN
-- CREAR UNA ENTIDAD CON PRIMARY KEY --> PRIMERA FORMA
CREATE TABLE EMPLEADO(
ID_EMPLEADO NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(100),
APELLIDO_P NVARCHAR2(100),
EDAD NUMBER,
PUESTO NVARCHAR2(100),
DEPARTAMENTO NVARCHAR2(100)
);

--DDL CON PRIMARY KEY -- SEGUNDA FORMA
CREATE TABLE EMPLEADO(
ID_EMPLEADO NUMBER,
NOMBRE NVARCHAR2(100),
APELLIDO_P NVARCHAR2(100),
EDAD NUMBER,
PUESTO NVARCHAR2(100),
DEPARTAMENTO NVARCHAR2(100),
PRIMARY KEY (ID_EMPLEAADO)
);
--DDL PRIMARY KEY -- TERCERA FORMA
CREATE TABLE EMPLEADO(
ID_EMPLEADO NUMBER,
NOMBRE NVARCHAR2(100),
APELLIDO_P NVARCHAR2(100),
EDAD NUMBER,
PUESTO NVARCHAR2(100),
DEPARTAMENTO NVARCHAR2(100),
CONSTRAINT EMPLEADO_PK PRIMARY KEY(ID_EMPLEADO)
);


