-- VISTAS O VIEWS -- SON UNA ALTERNATIVA PARA VISUALIZAR LOS DATOS O MAS TABKAS CREACO UNA TABLA VIRTUL
-- POR QUE LAS USAMOS?
--SON UTILIES PARA RESTYRINGIR EL ACCESO A LA BD , TAMBIEN PERMITE REALIZAR CONSULTAS DE MANERA SENCILLA

SELECT * FROM PADRE;
SELECT * FROM HIJO;

--VISTA

CREATE OR REPLACE VIEW V_PADRE_HIJO_DETALLE
AS
SELECT H.ID_HIJO, H.NOMBRE, H.APELLIDO, H.EDAD, NVL(H.HOBBIE, 'SIN HOBIE')AS HOBBIE, NVL(H.PADRE_ID,0)AS PADRE
FROM HIJO H LEFT JOIN PADRE P ON H.PADRE_ID = P.ID_PADRE;
---EN LAS VIEWS NO ES NECESARIO EL END PORQUE NO ES NECESARIO CERRA
--CONSULTAMOS LA VISTA
SELECT * FROM V_PADRE_HIJO_DETALLE;

--EJERCICIO CREAR UNA VISTA CON LA ENTIDAD MATERIA-ALUMNO UTILIZANDO FULL JOINY USAR MANEJADOR DE NULOS NULL(SIN , 0)
SELECT * FROM MATERIA;
SELECT * FROM ALUMNO;
--VISTA
CREATE OR REPLACE VIEW V_MATERIA_ALUMNO_DETALLE
AS
SELECT M.ID_MATERIA, M.NOMBRE AS MATERIA_NOM, M.NIVEL, M.CREDITOS, M.DOCENTES,
A.ID_ALUMNO, A.NOMBRE, A.APELLIDO, A.EDAD, A.CARRERA, NVL(A.MATERIA_ID,0)AS MATERIA
FROM MATERIA M FULL JOIN ALUMNO A ON M.ID_MATERIA = A.MATERIA_ID;

SELECT * FROM V_MATERIA_ALUMNO_DETALLE;

SELECT M.ID_MATERIA, M.NOMBRE, M.NIVEL, M.CREDITOS, M.DOCENTES,
A.ID_ALUMNO, A.NOMBRE, A.APELLIDO, A.EDAD, A.CARRERA, A.MATERIA_ID
FROM MATERIA M FULL JOIN ALUMNO A ON M.ID_MATERIA = A.MATERIA_ID;