-- triger simple
--DDL PARA LA ENTIDAD COMPUTADORA
CREATE TABLE COMPUTADORA(
   ID_COMPU NUMBER,
   MARCA NVARCHAR2(100),
   MODELO NVARCHAR2(100),
   RAM NUMBER,
   PROCESADOR NVARCHAR2(100),
   PRECIO NUMBER,
   CONSTRAINT COMPU_PK PRIMARY KEY(ID_COMPU)
);

--DDL PARA LA ENTIDAD BITACORA DE COMPUTADORA QUE REGISTRA CADA EVENTO

CREATE TABLE BIT_COMPUTADORA(
   ID_BIT NUMBER,--CLAVE PRIMARIA
   
   --VALORES NUEVOS (:NEW)
   ID_COMPU NUMBER,
   MARCA NVARCHAR2(100),
   MODELO NVARCHAR2(100),
   RAM NUMBER,
   PROCESADOR NVARCHAR2(100),
   PRECIO NUMBER,
   
   --VALORES VIEJOS (:OLD)
   MARCA_OLD NVARCHAR2(100),
   MODELO_OLD NVARCHAR2(100),
   RAM_OLD NUMBER,
   PROCESADOR_OLD NVARCHAR2(100),
   PRECIO_OLD NUMBER,
   
   
   --CAMPOS DE CONTROL
   USUARIO NVARCHAR2(20),
   FECHA_MOV DATE,
   MOVIMIENTO NVARCHAR2(100),
   
   CONSTRAINT BIT_COMPU_PK PRIMARY KEY(ID_BIT)
);
--DROP TABLE BIT_COMPUTADORA;
--CREACION DEL TRIGGER SIMPLE: SON BLOQUES ASOCIADOS A UNA TABLA Y ACTUAN ACORDE A UNADETERMINADA SENTENCIA DML
CREATE OR REPLACE TRIGGER TR_I_COMPUTADORA
AFTER INSERT ON COMPUTADORA
FOR EACH ROW 
DECLARE
LV_ID_BIT NUMBER;
LV_USUARIO NVARCHAR2(100);
LV_FECHA DATE;
     BEGIN
     SELECT USER INTO LV_USUARIO FROM DUAL; --OBTENER EL USUARIO
     SELECT SYSDATE INTO LV_FECHA FROM DUAL; --OBTENER LA FECHA DEL SISTEMA
     SELECT NVL(MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA; --OBTENER UN ID VALIDO
   
   INSERT INTO BIT_COMPUTADORA(ID_BIT, ID_COMPU, MARCA,MODELO,RAM, PROCESADOR,PRECIO,
   MARCA_OLD,MODELO_OLD,RAM_OLD, PROCESADOR_OLD,PRECIO_OLD, USUARIO,FECHA_MOV,MOVIMIENTO)
   VALUES(LV_ID_BIT,:NEW.ID_COMPU, :NEW.MARCA, :NEW.MODELO, :NEW.RAM, :NEW.PROCESADOR, :NEW.PRECIO, NULL, NULL, 0, NULL,
   0, LV_USUARIO,LV_FECHA,'INSERT');
  END TR_I_COMPUTADORA;
/
      
ALTER SESSION SET  NLS_DATE_FORMAT = 'DD/MM/YY HH24:MI:SS';

SELECT * FROM BIT_COMPUTADORA;
SELECT * FROM COMPUTADORA;
INSERT INTO COMPUTADORA VALUES(1, 'HP', 'PAVILOS', 16, 'INTEL CORE i9 12TH', 20000);
INSERT INTO COMPUTADORA VALUES(2, 'DELL', 'ALIEN', 32, 'INTEL CORE i9 10TH', 10000);
INSERT INTO COMPUTADORA VALUES(3, 'AZUS', 'VIVO', 8, 'INTEL CORE i5 5TH', 25000);
COMMIT;
DELETE FROM COMPUTADORA;
DELETE FROM BIT_COMPUTADORA;
--EJERCICIO REALIZAR EL TRIGGER PARA ACTUALIZAR(UPDATE) Y PARA ELIMINAR(DELETE) DE LA MISMA TABLA BIT_COMPUTADORA

CREATE OR REPLACE TRIGGER TR_U_COMPUTADORA
AFTER UPDATE ON COMPUTADORA
FOR EACH ROW 
DECLARE
LV_ID_BIT NUMBER;
LV_USUARIO NVARCHAR2(100);
LV_FECHA DATE;
     BEGIN
     SELECT USER INTO LV_USUARIO FROM DUAL; --OBTENER EL USUARIO
     SELECT SYSDATE INTO LV_FECHA FROM DUAL; --OBTENER LA FECHA DEL SISTEMA
     SELECT NVL(MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA; --OBTENER UN ID VALIDO
   
   INSERT INTO BIT_COMPUTADORA(ID_BIT, ID_COMPU, MARCA,MODELO,RAM, PROCESADOR,PRECIO,
   MARCA_OLD,MODELO_OLD,RAM_OLD, PROCESADOR_OLD,PRECIO_OLD, USUARIO,FECHA_MOV,MOVIMIENTO)
   VALUES(LV_ID_BIT,:NEW.ID_COMPU, :NEW.MARCA, :NEW.MODELO, :NEW.RAM, :NEW.PROCESADOR, :NEW.PRECIO, :OLD.MARCA, :OLD.MODELO, :OLD.RAM, :OLD.PROCESADOR,
   :OLD.PRECIO, LV_USUARIO,LV_FECHA,'UPDATE');
  END TR_U_COMPUTADORA;
/

UPDATE COMPUTADORA SET MARCA='AZUS', MODELO='VIVO', RAM =8, PROCESADOR='INTEL CORE i5 9TH', PRECIO = 54631 WHERE ID_COMPU=1; 
SELECT * FROM BIT_COMPUTADORA;
SELECT * FROM COMPUTADORA;
-------------

CREATE OR REPLACE TRIGGER TR_D_COMPUTADORA
AFTER DELETE ON COMPUTADORA
FOR EACH ROW 
DECLARE
LV_ID_BIT NUMBER;
LV_USUARIO NVARCHAR2(100);
LV_FECHA DATE;
     BEGIN
     SELECT USER INTO LV_USUARIO FROM DUAL; --OBTENER EL USUARIO
     SELECT SYSDATE INTO LV_FECHA FROM DUAL; --OBTENER LA FECHA DEL SISTEMA
     SELECT NVL(MAX(ID_BIT),0) + 1 INTO LV_ID_BIT FROM BIT_COMPUTADORA; --OBTENER UN ID VALIDO
   
   INSERT INTO BIT_COMPUTADORA(ID_BIT, ID_COMPU, MARCA,MODELO,RAM, PROCESADOR,PRECIO,
   MARCA_OLD,MODELO_OLD,RAM_OLD, PROCESADOR_OLD,PRECIO_OLD, USUARIO,FECHA_MOV,MOVIMIENTO)
   VALUES(LV_ID_BIT,NULL, NULL, NULL, 0, NULL, 0, :OLD.MARCA, :OLD.MODELO, :OLD.RAM, :OLD.PROCESADOR,
   :OLD.PRECIO, LV_USUARIO,LV_FECHA,'DELETE');
  END TR_D_COMPUTADORA;
/

DELETE FROM COMPUTADORA WHERE ID_COMPU =1;

SELECT * FROM BIT_COMPUTADORA;
SELECT * FROM COMPUTADORA;
-----------------------