

CREATE TABLE VIDEOJUEGO(
       ID_JUEGO NUMBER,
       NOMBRE NVARCHAR2(100),
       CATEGORIA NVARCHAR2(100),
       COSTO NUMBER,
       CONSTRAINT JUEGO_PK PRIMARY KEY(ID_JUEGO)
);

CREATE TABLE BIT_VIDEOJUEGO(
       ID_BIT NUMBER,
       
       -- VALORES NUEVOS
       ID_JUEGO NUMBER,
       NOMBRE NVARCHAR2(100),
       CATEGORIA NVARCHAR2(100),
       COSTO NUMBER,
       
       -- VALORES VIEJOS
       NOMBRE_OLD NVARCHAR2(100),
       CATEGORIA_OLD NVARCHAR2(100),
       COSTO_OLD NUMBER,
       
       --CAMPOS DE CONTROL
       USUARIO NVARCHAR2(20),
       FECHA_MOV DATE,
       MOVIMIENTO NVARCHAR2(100),
      
       CONSTRAINT BIT_JUEGO_PK PRIMARY KEY(ID_BIT)
);
SELECT * FROM VIDEOJUEGO;
SELECT * FROM  BIT_VIDEOJUEGO;

--SENTENCIA PARA VIDEOJUEGO
CREATE SEQUENCE S_ID_BIT_JUEGO
START WITH 1
MAXVALUE 9999
MINVALUE 1
NOCYCLE;
/
--SELECT S_ID_BIT_JUEGO.NEXTVAL FROM DUAL;
----------------

CREATE OR REPLACE TRIGGER TR_MULTIPLE_VIDEOJUEGO
AFTER INSERT OR UPDATE OR DELETE ON VIDEOJUEGO
FOR EACH ROW
DECLARE
LV_ID_BIT NUMBER;
LV_USUARIO NVARCHAR2(100);
LV_FECHA DATE;
  BEGIN
      SELECT S_ID_BIT_JUEGO.NEXTVAL,USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;
      --INSERT
       IF INSERTING THEN
       INSERT INTO BIT_VIDEOJUEGO(ID_BIT, ID_JUEGO, NOMBRE, CATEGORIA, COSTO, 
       NOMBRE_OLD, CATEGORIA_OLD, COSTO_OLD, USUARIO, FECHA_MOV, MOVIMIENTO)
       VALUES(LV_ID_BIT, :NEW.ID_JUEGO, :NEW.NOMBRE, :NEW.CATEGORIA, :NEW.COSTO, NULL, NULL, 0, 
       LV_USUARIO, LV_FECHA, 'INSERT');
       
       --UPDATE
       ELSIF UPDATING THEN
       INSERT INTO BIT_VIDEOJUEGO(ID_BIT, ID_JUEGO, NOMBRE, CATEGORIA, COSTO, 
       NOMBRE_OLD, CATEGORIA_OLD, COSTO_OLD, USUARIO, FECHA_MOV, MOVIMIENTO)
       VALUES(LV_ID_BIT, :NEW.ID_JUEGO, :NEW.NOMBRE, :NEW.CATEGORIA, :NEW.COSTO, :OLD.NOMBRE, :OLD.CATEGORIA, :OLD.COSTO,
       LV_USUARIO, LV_FECHA, 'UPDATE');
       
       --DELETE
       ELSIF DELETING THEN
       INSERT INTO BIT_VIDEOJUEGO(ID_BIT, ID_JUEGO, NOMBRE, CATEGORIA, COSTO, 
       NOMBRE_OLD, CATEGORIA_OLD, COSTO_OLD, USUARIO, FECHA_MOV, MOVIMIENTO)
       VALUES(LV_ID_BIT, :OLD.ID_JUEGO, NULL, NULL, 0, :OLD.NOMBRE, :OLD.CATEGORIA, :OLD.COSTO,
       LV_USUARIO, LV_FECHA, 'DELETE');
        END IF;
   END TR_MULTIPLE_VIDEOJUEGO;
/
    INSERT INTO VIDEOJUEGO VALUES(1, 'GOD OF WAR', 'C', 1599); 
    INSERT INTO VIDEOJUEGO VALUES(2, 'TLOU', 'B', 1299); 
    INSERT INTO VIDEOJUEGO VALUES(3, 'MARIO', 'A', 700);
    COMMIT;
    SELECT * FROM VIDEOJUEGO;
    SELECT * FROM BIT_VIDEOJUEGO;
    UPDATE VIDEOJUEGO SET NOMBRE ='DIOS', CATEGORIA ='B', COSTO =321 WHERE ID_JUEGO =1;
    DELETE VIDEOJUEGO WHERE ID_JUEGO =2;