-- AGREGAR REGISTRO A MI TABLA EMPLEADO
INSERT INTO EMPLEADO VALUES(1, 'JULIO', 'MARTINEZ', 29, 'CONTADOR', 'DEPARTAMENTO DE FINANZAS');
INSERT INTO EMPLEADO VALUES(2, 'MARCOS', 'ENRIQUEZ', 59, 'ABOGADO', 'DEPARTAMENTO FAMILIAR');
INSERT INTO EMPLEADO VALUES(3, 'MACARIO', 'PALMA', 22, 'CONTADOR', 'DEPARTAMENTO DE FINANZAS');
INSERT INTO EMPLEADO VALUES(4,'RODRIGO','HERNANDEZ',35,'INGENIERO','DEPARTAMENTO DE REDES');
INSERT INTO EMPLEADO VALUES(5,'JUANITO', 'PEREZ',25, 'COINTROL DE CALIDAD', 'DEPARTAMENT DE CALIDAD');
INSERT INTO EMPLEADO VALUES(6, 'NAHUM', 'ROSAS', 20, 'INGENIERO', 'MANTENIMIENTO');
COMMIT;

SELECT * FROM EMPLEADO;

--FUNCIONES

--MODIFICAR O CAMBIAR EL NOMBRE DE LA COLUMNA

ALTER TABLE EMPLEADO RENAME COLUMN APELLIDO_P TO APELLIDO_PATERNO;

--DML ACTUALIZAR

UPDATE EMPLEADO SET NOMBRE = 'JUAN' WHERE ID_EMPLEADO = 5;

--ORDER BY
--MENOR A MAYOR
SELECT * FROM EMPLEADO ORDER BY EDAD ASC;
--MAYOR A MENOR
SELECT * FROM EMPLEADO ORDER BY EDAD DESC;

--BUSQUEDA DE INFORMACION CON CARATERES
--BUSCAR EMPLEADOS QUE EMPIEZA CON LETRA A
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE 'J%';

--BUSCAR EMPLEADO QUE SU NOMBRE CONTENGA LA LETRA I
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE '%I%';

-- EMPLEADOS QUE SU NOMBRE TERMINE CON LA LETRA O
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE '%O';

--BUSCAR EMPLEADOS QUE SU NOMBRE NO SEA NULL
SELECT * FROM EMPLEADO WHERE NOMBRE IS NOT NULL;

--USO DE LA TABLA DUAL

SELECT 5 + 5 AS SUMA FROM DUAL;

--USO DE LA FUNCION LENGHT
SELECT  LENGTH('ESTA ES UNA CADENA DE PRUEBA PARA EL USO DE LENGTH') AS TAMINIO FROM DUAL;

--BUSCAR CON MAS CONDICIONES
--BUSCAR EMPLEADOS QUE SEAN MAYORES A 25
SELECT * FROM EMPLEADO WHERE EDAD > 25;
--BUSCAR EMPLEADOS MENORES DE 30
SELECT * FROM EMPLEADO WHERE EDAD < 30 ORDER BY EDAD ASC;

--BUSCAR QUE SEAN MAYORES DE 24 Y MENORES DE 28 SENTENCIA AND
SELECT * FROM EMPLEADO WHERE EDAD > 24 AND EDAD <28;

--RANGO BETWEEN
SELECT * FROM EMPLEADO WHERE EDAD BETWEEN 24 AND 28 ;

--BUSCAR EMPLEADOS CON EL ID 1,3,5
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO = 1 OR ID_EMPLEADO = 3 OR ID_EMPLEADO = 5;

--USO DE LA FUNCION IN
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO IN(1,3,5);

--USO DE LA FUNCION GROP BY Y COUNT
SELECT DEPARTAMENTO FROM EMPLEADO GROUP BY DEPARTAMENTO;
SELECT DEPARTAMENTO, COUNT(ID_EMPLEADO) AS NO_EMPLEADO FROM EMPLEADO WHERE DEPARTAMENTO IS NOT NULL GROUP BY DEPARTAMENTO;

--CONTAR EMPLEADOS QUE TENGAS MAS DE 25
SELECT COUNT(ID_EMPLEADO) AS TOTAL_EMPLEADOS FROM EMPLEADO WHERE EDAD > 25;

--FUNCION DE AGREGACION SUM
SELECT SUM(EDAD) AS SUMA_EDADES FROM EMPLEADO WHERE APELLIDO_PATERNO LIKE'%A%';

--FUNCION AGREGACION MAX
SELECT MAX(EDAD) AS EDAD_MAXIMA FROM EMPLEADO;
--FUNCION DE AGREGACION MIN
SELECT MIN(EDAD) AS EDAD_MINIMA FROM EMPLEADO;
--FUNCION DE AGREGACION AVG
SELECT AVG(EDAD) EDAD_PROMEDIO FROM EMPLEADO;

--USO DE LA FUNCION ROUND
SELECT ROUND(AVG(EDAD), 2) AS PROMEDIO_EDAD FROM EMPLEADO;

--USO DE TO CHAR CON FORMATO
SELECT TO_CHAR (AVG(EDAD), 'FM999.0') AS PROMEDIO_EDAD FROM EMPLEADO;

--DAR UN FORMATO DIFERENTE
--FUNCION CONCAT
SELECT CONCAT(CONCAT(CONCAT(CONCAT('EL EMPLEADO ', '' ), NOMBRE), ' ' ), APELLIDO_PATERNO) AS DETALLE FROM EMPLEADO;

--USO DE PIPE O BARRA VERTICAL
--SELECT 'EL EMPLEADO' ||NOMBRE|| '' ||APELLIDO_PATERNO || ' DE EDAD' || EDAD || ' ANIOS, TRABAJA EN EL DEPARTAMENTO' || DEPARTAMENTO || 'COMO'' ||
--PUESTO AS DETALLE FROM EMPLEADO ;
SELECT 'EL EMPLEADO' || NOMBRE || '' || APELLIDO_PATERNO || 'DE EDAD' ||EDAD || 'ANIOS, TRABAJA EN EL DEPARTAMENTO'|| DEPARTAMENTO || 'COMO' || 
PUESTO AS DETALLE FROM EMPLEADO;

-- CONSULTA DOBLE
SELECT * FROM EMPLEADO WHERE
EDAD = (
SELECT MIN(EDAD)
FROM EMPLEADO
WHERE DEPARTAMENTO = 'DEPARTAMENTO DE FINANZAS'
);

--SUB CONSULTA
SELECT * FROM EMPLEADO WHERE
EDAD=(
SELECT MAX(EDAD)
FROM EMPLEADO
WHERE DEPARTAMENTO = ('DEPARTAMENTO DE FINANZAS'
)
) AND DEPARTAMENTO = 'DEPARTAMENTO DE FINANZAS';

