--Scropst para la creacion de la tabla del micro del micro servicio EVENTO

CREATE TABLE EVENTO(
    ID_EVENTO NUMBER,
    NOMBRE NVARCHAR2(100),
    FECHA_HORA DATE,
    ESTRELLAS_INVITADAS NVARCHAR2(100),
    TOTAL_ASISTENCIA NUMBER,
    CONSTRAINT EVENTO_PK PRIMARY KEY(ID_EVENTO) 
);

INSERT INTO EVENTO VALUES(1, 'hola', TO_DATE('12/05/2025  12:00', 'DD/MM/YYYY HH24:MI'), 'leon', 500);
COMMIT;
delete evento;
select * from evento;


select * from costo;

--dll para el microservidor de ubicacion 

CREATE TABLE UBICACION(
   UBICACION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   EVENTO_ID NUMBER,
   NOMBRE_LUGAR NVARCHAR2(100),
   UBICACION NVARCHAR2(100)
);

INSERT INTO UBICACION(EVENTO_ID, NOMBRE_LUGAR, UBICACION)
VALUES(1, 'CENTRO DE CONVENCIONES', 'AV. REFORMA 123');
COMMIT;
SELECT * FROM UBICACION;
select * from usuario;