select * from veterinaria;

select * from hotel;

CREATE TABLE RESPONSABLES(
   ID_RESPONSABLE NUMBER GENERATED ALWAYS AS IDENTITY,
   NOMBRE NVARCHAR2(50),
   CONTACTO NUMBER,
   VETERINARIA_ID NUMBER,
   CONSTRAINT PK_RESPON PRIMARY KEY(ID_RESPONSABLE)
);
drop TABLE MASCOTAS;
COMMIT;
SELECT * FROM RESPONSABLES;

CREATE TABLE MASCOTAS(
    ID_MASCOTA NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE NVARCHAR2(15),
    RAZA NVARCHAR2(15),
    EDAD NUMBER,
    CITA_RAZON NVARCHAR2(100),
    CLIENTE_ID NUMBER,
    RESPONSABLE_ID NUMBER,
    VETERINARIA_ID NUMBER,
    CONSTRAINT MASCOTAS_PK PRIMARY KEY(ID_MASCOTA)
);

DROP TABLE MASCOTAS;
COMMIT;
SELECT * FROM MASCOTAS;
/*
CREATE TABLE VETERINARIAS(
   ID_VETERINARIA NUMBER GENERATED ALWAYS AS IDENTITY,
   NOMBRE NVARCHAR2(50),
   DIRECCION NVARCHAR2(50),
   TELEFONO NUMBER,
   VETERINARIA_ID NUMBER,
   CONSTRAINT PK_VETERI PRIMARY KEY(ID_VETERINARIA)
);
CREATE TABLE CLIENTES(
   ID_CLIENTE NUMBER GENERATED ALWAYS AS IDENTITY,
   NOMBRE NVARCHAR2(50),
   DIRECCION NVARCHAR2(50),
   CONTACTO NUMBER,
   VETERINARIA_ID NUMBER,
   CONSTRAINT PK_CLIEN PRIMARY KEY(ID_CLIENTE)
);
*/